esphome:
  name: testespoilgauge

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.1.2
    platform_version: https://github.com/stintel/platform-espressif32#esp32-c6-test

# Enable logging
logger:

packages:
  wifi: !include wifi.yaml  # include you wifi configuration here

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

captive_portal:

uart:
  rx_pin: GPIO4 # default on esp32-c6 -- connect to US-100 rx
  tx_pin: GPIO5 # default on esp32-c6 -- connect to US-100 tx
  baud_rate: 9600
  debug:
    direction: RX
    dummy_receiver: true
    sequence:
      - lambda: |-
          UARTDebug::log_string(direction, bytes);
          float distance=0;
          float oil_left=0;

          //Sample binary / hex data
          if (bytes.size()==2) {
              distance = (bytes[0] * 256 + bytes[1]) / 10 ;
              oil_left = id(tank_depth).state - distance;
              id(binData).publish_state( oil_left );
          }

number:
- platform: template
  name: "Oil Tank Depth"  # Can be set from Homeassistant frontend
  id: tank_depth
  min_value: 30
  max_value: 400
  step: 1
  initial_value: 134 # Depth of my own oil tank, sorry
  unit_of_measurement: "cm"
  optimistic: true

sensor:
  - platform: template
    id: binData
    update_interval: 60s
    name: "Oil Gauge"
    accuracy_decimals: 1
    unit_of_measurement: "cm"

interval:
  - interval: 30s
    then:
      - uart.write: [0x55]
      - delay: 500ms
