esphome:
  name: testespoilgauge

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.1.2
    platform_version: https://github.com/stintel/platform-espressif32#esp32-c6-test

# Enable logging
logger:

packages:
  wifi: !include wifi.yaml  # include you wifi configuration here

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testespoilgauge Fallback Hotspot"
    password: !secret ap_password

captive_portal:
    
